### ISSUE TITLE
conventional-changelog-conventionalcommits@^7.0.0 not working with Lerna@7.2.0

### ISSUE THREAD

**Issue by kerryj89** [conventional-changelog/conventional-changelog#1116]
I upgraded to `conventional-changelog-conventionalcommits@7.1.0` and use it with `Lerna@7.2.0` (latest as of this writing), and it just freezes up at:

```
lerna info getChangelogConfig Successfully resolved preset "conventional-changelog-conventionalcommits"
```

So I downgraded it to `conventional-changelog-conventionalcommits@7.0.0` and was able to see a little more about the error:

```
lerna info getChangelogConfig Auto-prefixing conventional-changelog preset "conventional-changelog-conventionalcommits"
lerna WARN getChangelogConfig Cannot find module './constants'
lerna WARN getChangelogConfig Require stack:
lerna WARN getChangelogConfig - /Users/someone/.nvm/versions/node/v18.17.1/lib/node_modules/conventional-changelog-conventionalcommits/index.js
lerna WARN getChangelogConfig - /Users/someone/.nvm/versions/node/v18.17.1/lib/node_modules/lerna/dist/index.js
lerna WARN getChangelogConfig - /Users/someone/.nvm/versions/node/v18.17.1/lib/node_modules/lerna/dist/cli.js
lerna ERR! EPRESET Unable to load conventional-changelog preset 'conventional-changelog-conventionalcommits'
```

Downgrading to `conventional-changelog-conventionalcommits@6.1.0` allowed Lerna to chug along.

Is there something that stands out here?  Please let me know if I should be filing an issue with Lerna instead.  Thanks!

**Comment by dangreen** [comment]
@kerryj89 Hi. [conventional-changelog-conventionalcommits v7.0.0 release](https://github.com/conventional-changelog/conventional-changelog/releases/tag/conventional-changelog-conventionalcommits-v7.0.0) contains some breaking changes. Please open issue in Lerna repo with request to support new preset version,

**Comment by jlipps** [comment]
Created an issue at the Lerna repo: https://github.com/lerna/lerna/issues/3871
